
[rofi]
pre_command = "echo 'Preserve rofi config'"

[[rofi.dependency]]
dnf = ["rofi"] # Fedora's rofi has upstream Wayland support built in
pacman = ["rofi"]

[[rofi.files]]
action = "preserve"
source_root = "Configs/.config"
target_root = "${XDG_CONFIG_HOME}"
paths = "rofi"
